name: Deploy Docs to GitHub

on:
  push:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/ghpages.yml'
    - 'CONTRIBUTING.md'
    - 'COPYING'
    - '.gitignore'
    - '.editorconfig'
    - 'NEWS'
    - 'README.md'
    - 'style_unify'

  pull_request:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/ghpages.yml'
    - 'CONTRIBUTING.md'
    - 'COPYING'
    - '.gitignore'
    - '.editorconfig'
    - 'NEWS'
    - 'README.md'
    - 'style_unify'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Get latest tag'
      run: echo "GIT_LATEST_TAG=$(git tag | grep '^[0-9]\+\.[0-9]\+\?\.[0-9]\+\?$' | sort -V -r | head -n1)" >> $GITHUB_ENV
    - name: 'Install prerequisites'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libdrm-dev \
          doxygen \
          meson \
    - name: 'Configure'
      run: meson setup _build -D enable_docs=true
    - name: 'Build the Docs'
      run: meson compile -C _build
    - name: 'Upload the artifacts'
      uses: actions/upload-pages-artifact@v1
      with:
        path: "_build/doc/html-out"

  deploy:
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04
    steps:
    - name: 'Deploy to GitHub Pages'
      if: ${{ github.ref_name }} == ${{ env.GIT_LATEST_TAG }}
      id: deployment
      uses: actions/deploy-pages@v1
