name: Deploy Docs to GitHub

on:
  release:
    types: [published]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      run: git fetch --tags
    - name: 'Get latest tag'
      run: echo "GIT_LATEST_TAG=$(git tag | grep '^[0-9]\+\.[0-9]\+\?\.[0-9]\+\?$' | sort -V -r | head -n1)" >> $GITHUB_ENV
    - name: 'Install prerequisites'
      if: ${{ github.ref_name }} == ${{ env.GIT_LATEST_TAG }}
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libdrm-dev \
          doxygen \
          meson \
    - name: 'Build the Docs'
      if: ${{ github.ref_name }} == ${{ env.GIT_LATEST_TAG }}
      run: meson setup _build -D enable_docs=true && meson compile -C _build
    - name: 'Upload the artifacts'
      if: ${{ github.ref_name }} == ${{ env.GIT_LATEST_TAG }}
      uses: actions/upload-pages-artifact@v1
      with:
        path: "_build/doc/html-out"

  deploy:
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04
    steps:
    - name: 'Deploy to GitHub Pages'
      id: deployment
      uses: actions/deploy-pages@v1
